
esphome:
  name: "water-flow-sensor" #设备名称
  platform: ESP8266   #设备平台
  board: nodemcuv2  #主板类型

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "AbZDG0VKLstc+crcITmljANpV1A8jGb2wloYMUU3KvU="  #这个创建一个新的sensor会自动生成，直接用随机生成的即可。

ota:
  password: ""  #ota升级密码，可以不用写

wifi:
  ssid: "家里wifi名称"
  password: "家里wifi密码"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "water flow sensor Hotspot" #永辉回调的热点wifi名称和密码，随便写
    password: "自定义密码"

captive_portal:


web_server:  ## web控制，添加了这2行，就可以在网页端打开设备ip;
  port: 80
  

mqtt:
  broker: 你mqtt IP
  username: mqtt账户
  password: mqtt密码


sensor:
  - platform: pulse_counter
    pin: D1
    name: "water_speed"
    id: water
    unit_of_measurement: 'L/Min'
    update_interval: 5s #上报时间间隔
    filters:
      - multiply: 0.0043  #一升水330个脉冲1/330=0.00303030303030303，厂商给的参数未必就适合你的环境，可以根据家里用水环境适当调整，和水表用量接近即可。

      
  - platform: total_daily_energy
    name: "daily water use"
    power_id: water
    unit_of_measurement: 'L'
    device_class: water
    filters:
      - multiply: 60  #1分钟换算成一秒，升换算成方=1*60/1000
    accuracy_decimals: 2


  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950   #B值
      reference_temperature: 25°C
      reference_resistance: 50kOhm   #热敏电阻阻值
    name: water Temperature
 
  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm    #参考电阻阻值
    #name: Resistance Sensor
  - platform: adc
    id: source_sensor
    pin: A0
    filters:
       - multiply: 3.3   #电压转换，MCU开发板的adc电压是0-3.3v
    update_interval: never
switch:
  - platform: gpio
    pin: D0
    id: ntc_vcc
 
interval:
  - interval: 10s     #参考电阻通电切换
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc

time:
  - platform: sntp
    timezone: Asia/Shanghai
    id: my_time    

        
